Repository keep-the-receipts/data-extraction, pull requests merged in 2020-11, with the labels that each got.

#323 Update and rename National Departments/Department of Communications a…
  National Departments/Department of Communications and Digital Technologies/MISA Accounting Officer's Report_PPE Procurement 07 Aug 2020-other.csv
  National Departments/Department of Cooperative Governance (DCoG)/MISA Accounting Officer's Report_PPE Procurement 07 Aug 2020-other.csv
Labels: Cleaning

#307 Update and rename NATIONAL PROSECUTING AUTHORITY_PPE - 1 Apr 2020 to …
  NATIONAL PROSECUTING AUTHORITY_PPE - 1 Apr 2020 to 31 March 2021 - Finalized as at 07-08-2020.csv
  National Departments/National Prosecuting Authority/PPE - 1 Apr 2020 to 31 March 2021 - Finalized as at 07-08-2020.csv
Labels: Cleaning, hacktoberfest-accepted, question

#312 Update and rename tabula-STATS SA - Annexure A - Covid 10 Related Act…
  National Departments/The Presidency/STATS SA - Annexure A - Covid 10 Related Activities Procurement 31 July 2020.csv
  tabula-STATS SA - Annexure A - Covid 10 Related Activities Procurement 31 July 2020.csv
Labels: Cleaning, hacktoberfest-accepted, question

#330 Update and rename PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure R…
  National Departments/Department of Public Enterprises/PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure Report-building-sanitisation - pass 1.csv
  National Departments/Department of Public Enterprises/PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure Report-building-sanitisation.csv
Labels: Cleaning

#332 Update and rename PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure R…
  National Departments/Department of Public Enterprises/PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure Report-procurement-service-providers - pass 1.csv
  National Departments/Department of Public Enterprises/PUBLIC ENTERPRISES - 11082020 Covid19 Expenditure Report-procurement-service-providers.csv
Labels: Cleaning

#319 Update and rename The Presidency - Statistics South Africa (Stats SA)…
  National Departments/Statistics South Africa (Stats SA) pass 1
  The Presidency - Statistics South Africa (Stats SA) pass 1
Labels: Cleaning, hacktoberfest-accepted, question

#317 Update and rename HIGHER EDUCATION AND TRAINING and NAT SKILLS FUND -…
  National Departments/Department of Higher Education and Training (DHET)/HIGHER EDUCATION AND TRAINING and NAT SKILLS FUND DHET-PROCUREMENT OF PPEs AS AT 06 AUGUT 2020 - pass 1.csv
Labels: Cleaning, hacktoberfest-accepted

#336 Update and rename HIGHER EDUCATION AND TRAINING and NAT SKILLS FUND -…
  National Departments/Department of Higher Education and Training (DHET)/HIGHER EDUCATION AND TRAINING and NAT SKILLS FUND - COVID-19 PROCUREMENTS- NSF- PROCUREMENT OF PPEs AS AT 06 AUGUT 2020 - pass 1.csv
Labels: Cleaning

#328 Update and rename SCIENCE and INNOVATION and ENTITIES - COVID19 PROCU…
  National Departments/Department of Science and Innovation (DSI)/DSI and ENTITIES - COVID19 PROCUREMENTS - pass 1.csv
  National Departments/Department of Science and Innovation (DSI)/SCIENCE and INNOVATION and ENTITIES - COVID19 PROCUREMENTS.csv
Labels: Cleaning

#318 Update and rename NATIONAL TREASURY - Procurement during the period o…
  NATIONAL TREASURY - Procurement during the period of the COVID-19 pandemic.csv
  National Departments/National Treasury/Procurement during the period of the COVID-19 pandemic.csv
Labels: Cleaning, hacktoberfest-accepted

#321 Update and rename tabula-CENTRE FOR PUBLIC SERVICE INNOVATION (CPSI) …
  National Departments/Department of Public Service and Administration (DPSA)/CENTRE FOR PUBLIC SERVICE INNOVATION (CPSI) - Covid19 expenditure August 2020.csv
  tabula-CENTRE FOR PUBLIC SERVICE INNOVATION (CPSI) - Covid19 expenditure August 2020.csv
Labels: Cleaning, hacktoberfest-accepted

#315 Update and rename FILM AND PUBLICATION BOARD - Procurement of COVID-1…
  FILM AND PUBLICATION BOARD - Procurement of COVID-19 Related Goods and Services.csv
  National Departments/Department of Communications and Digital Technologies (DCDT)/Film and Publications Board (FPB) Procurement of COVID-19 Related Goods and Services.csv
Labels: Cleaning, hacktoberfest-accepted, question

#326 Update and rename WOMEN YOUTH AND PERSONS WITH DISABILITY - REPORT ON…
  National Departments/Department of Women, Youth and Persons with Disabilities (DWYPD)/WOMEN YOUTH AND PERSONS WITH DISABILITY - REPORT ON COVID 19 SPENT 07082020.csv
  WOMEN YOUTH AND PERSONS WITH DISABILITY - REPORT ON COVID 19 SPENT 07082020.csv
Labels: Cleaning

#333 Update and rename tabula-Onderstepoort Biological Products COVID Proc…
  National Departments/Department of Agriculture, Land Reform and Rural Development (DALRRD)/Onderstepoort Biological Products (OBP) COVID Procurement Report - pass 1.csv
  National Departments/Department of Agriculture, Land Reform and Rural Development (DALRRD)/tabula-Onderstepoort Biological Products COVID Procurement Report.csv
Labels: Cleaning

#302 Update and rename Department of Health (DoH) – Pass 1.csv to National…
  Department of Health (DoH) – Pass 1.csv
  National Departments/Department of Health/National Department of Health Pass 1.csv
Labels: Cleaning, hacktoberfest-accepted

#316 Update and rename BASIC EDUCATION - Covid19 Expenditure.csv to Nation…
  BASIC EDUCATION - Covid19 Expenditure.csv
  National Departments/Department of Basic Education (DBE)/BASIC EDUCATION - Covid 19 Expenditure pass 1.csv
Labels: Cleaning, hacktoberfest-accepted

#329 Update and rename National Departments/Department of Social Developme…
  National Departments/Department of Social Development (DSD)/South Africa Social Security Agency/tabula-SSA - COVID19 PPE Procurement Status Report with receipt dates.csv
  National Departments/State Security Agency (SSA)/SSA - COVID19 PPE Procurement Status Report with receipt dates.csv
Labels: Cleaning

#160 Create tabula-SASSA - Covid 19 Procurement March 2020 - Head Office a…
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-EC.csv
Labels: hacktoberfest-accepted

#149 Create tabula-SASSA - Covid 19 Procurement March 2020 - Head Office a…
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-KZN.csv
Labels: hacktoberfest-accepted

#342 Update and rename SASSA - Head Office and Regions PPE only-GP.csv to …
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Head Office and Regions PPE only-GP.CSV
  SASSA - Head Office and Regions PPE only-GP.csv
Labels: Cleaning

#340 Update SASSA - Covid 19 Procurement March 2020 -MP COVID 19 STANDARD …
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 -MP COVID 19 STANDARD ORDERS 2020-2021.csv
Labels: Cleaning

#343 Rename SASSA - Head Office and Regions PPE only-NW.CSV to National De…
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Head Office and Regions PPE only-NW.CSV
Labels: Cleaning

#341 Update and rename tabula-SASSA - Covid 19 Procurement March 2020 - He…
  National Departments/Department of Social Development (DSD)/South Africa Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-Procurement-progress.csv
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-Procurement-progress.csv
Labels: Cleaning

#345 Update and rename tabula-SASSA - Covid 19 Procurement March 2020 - He…
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-FS.csv
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-FS.csv
Labels: Cleaning

#346 Update and rename tabula-SASSA - Covid 19 Procurement March 2020 - He…
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-HO.csv
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-HO.csv
Labels: Cleaning

#314 Update and rename tabula-SASSA - Covid 19 Procurement March 2020 - He…
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 - WC.csv
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-WC.csv
Labels: Cleaning, hacktoberfest-accepted

#347 Update and rename tabula-SASSA - Covid 19 Procurement March 2020 - He…
  National Departments/Department of Social Development (DSD)/South African Social Security Agency (SASSA)/SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-NC.csv
  tabula-SASSA - Covid 19 Procurement March 2020 - Head Office and Regions PPE only-NC.csv
Labels: Cleaning

#325 Update and rename tabula-PUBLIC WORKS AND INFRASTRUCTURE - Informatio…
  National Departments/Department of Public Works and Infrastructure (DPWI)/PUBLIC WORKS AND INFRASTRUCTURE - Information regarding suppliers and amounts related to COVID19 - pass 1.csv
  tabula-PUBLIC WORKS AND INFRASTRUCTURE - Information regarding suppliers and amounts related to COVID19.csv
Labels: Cleaning

#320 Update and rename The Presidency - Media Development and Diversity Ag…
  National Departments/The Presidency/Media Development and Diversity Agency pass 1
  The Presidency - Media Development and Diversity Agency (MDDA) pass 1
Labels: Cleaning, hacktoberfest-accepted, question

#334 Update and rename tabula-PSIRA - PPE PROCUREMENT - Goods and services…
  National Departments/South African Police Service (SAPS)/Private Security Industry Regulatory Authority (PSIRA) - PPE PROCUREMENT - Goods and services procured - pass 1.csv
  National Departments/South African Police Service (SAPS)/tabula-PSIRA - PPE PROCUREMENT - Goods and services procured.csv
Labels: Cleaning, question

#350 Update and rename tabula-PSIRA - PPE PROCUREMENT - DECONTAMINATION SE…
  National Departments/South African Police Service (SAPS)/PSIRA - PPE PROCUREMENT - DECONTAMINATION SERVICES AFTER REPORTED CASES.csv
  National Departments/South African Police Service (SAPS)/tabula-PSIRA - PPE PROCUREMENT - DECONTAMINATION SERVICES AFTER REPORTED CASES.csv
Labels: Cleaning

#352 Update and rename tabula-CSPS - PPE PROCUREMENT.csv to CSPS - PPE PRO…
  National Departments/South African Police Service (SAPS)/CSPS - PPE PROCUREMENT.csv
  National Departments/South African Police Service (SAPS)/tabula-CSPS - PPE PROCUREMENT.csv
Labels: Cleaning

#356 Update Free State Health - 4.csv
  Provincial Government/Free State/Health/Free State Health - 4.csv
Labels: Cleaning

#357 Update Free State Health - 5.csv
  Provincial Government/Free State/Health/Free State Health - 5.csv
Labels: Cleaning

#358 Update Free State Health - 6.csv
  Provincial Government/Free State/Health/Free State Health - 6.csv
Labels: Cleaning

#360 Update Free State Health - 7.csv
  Provincial Government/Free State/Health/Free State Health - 7.csv
Labels: Cleaning

#244 Create tabula-FREE STATE FINANCE TENDER BULLETIN - 1.csv
  tabula-FREE STATE FINANCE TENDER BULLETIN - 1.csv
Labels: hacktoberfest-accepted

#361 Update FORESTRY, FISHERIES AND ENVIRONMENT - Covid19 Procurement for …
  National Departments/Department of Environment, Forestry and Fisheries (DEFF)/FORESTRY, FISHERIES AND ENVIRONMENT - Covid19 Procurement for 2020-21 FY as of 07 August 2020.csv
Labels: Cleaning

#362 Update and rename BROADBAND INFRACO - Response Procurement Spending D…
  BROADBAND INFRACO - Response Procurement Spending During COVID-19 Pandemic 20200824.csv
  National Departments/Department of Telecommunications and Postal Services (DTPS)/BROADBAND INFRACO - Response Procurement Spending During COVID-19 Pandemic 20200824.csv
Labels: Cleaning

#363 Update NAMC - Report Procurement of PPEs.csv
  National Departments/Department of Agriculture, Land Reform and Rural Development (DALRRD)/NAMC - Report Procurement of PPEs.csv
Labels: Cleaning

#364 Update SOCIAL DEVELOPMENT - COVID LIST.csv
  National Departments/Department of Social Development (DSD)/SOCIAL DEVELOPMENT - COVID LIST.csv
Labels: Cleaning

#365 Update SAPS - PPE PROCUREMENT (DETAILS).csv
  National Departments/South African Police Service (SAPS)/SAPS - PPE PROCUREMENT (DETAILS).csv
Labels: Cleaning

#366 Update and rename tabula-SIU - Response to Parliamentary question on …
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/SIU - Response to Parliamentary question on Covid and PPE-ppe.csv
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/tabula-SIU - Response to Parliamentary question on Covid and PPE-ppe.csv
Labels: Cleaning

#367 Update and rename tabula-SIU - Response to Parliamentary question on …
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/SIU - Response to Parliamentary question on Covid and PPE-other.csv
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/tabula-SIU - Response to Parliamentary question on Covid and PPE-other.csv
Labels: Cleaning

#369 Update and rename FREE STATE HUMAN SETTLEMENTS.csv to FREE STATE HUMA…
  Provincial Government/Free State/Human Settlements/FREE STATE HUMAN SETTLEMENTS pass 1.csv
  Provincial Government/Free State/Human Settlements/FREE STATE HUMAN SETTLEMENTS.csv
Labels: Cleaning

#327 Update and rename Department of Justice and Constitutional Developmen…
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/Department of Justice and Constitutional Development (DoJ&CD) - pass 1.csv
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/Department of Justice and Constitutional Development (DoJ&CD).csv
Labels: Cleaning

#371 Update and rename tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - dis…
  Provincial Government/Free State/Public Works and Infrastructure/Disnfection of Government Buildings.CSV
  Provincial Government/Free State/Public Works and Infrastructure/tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - disnfect.CSV
Labels: Cleaning

#375 Update and rename Provincial Government/Free State/Public Works and I…
  Provincial Government/Free State/Public Works and Infrastructure/FREE STATE PUBLIC WORKS INFRASTRUCTURE - privately owned sites and expenditure pass 1.CSV
Labels: Cleaning

#376 Update and rename tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - fie…
  Provincial Government/Free State/Public Works and Infrastructure/FREE STATE PUBLIC WORKS INFRASTRUCTURE - field hospital construction pass 1.CSV
  Provincial Government/Free State/Public Works and Infrastructure/tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - field hospital construction.CSV
Labels: Cleaning

#377 Update and rename tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - sec…
  Provincial Government/Free State/Public Works and Infrastructure/FREE STATE PUBLIC WORKS INFRASTRUCTURE - security companies appointed.CSV
  Provincial Government/Free State/Public Works and Infrastructure/tabula-FREE STATE PUBLIC WORKS INFRASTRUCTURE - security companies appointed
Labels: Cleaning

#378 Update and rename The Presidency Department of Planning, Monitoring a…
  The Presidency Department of Planning, Monitoring and EvaluationPass 1.csv
  The Presidency/Department of Planning, Monitoring and Evaluation pass 1.csv
Labels: Cleaning

#380 Update Payments pass 1.CSV
  National Departments/The Presidency/Government Communication and Information System (GCIS)/Payments pass 1.CSV
Labels: Cleaning

#383 Update Commitments pass 1.CSV
  National Departments/The Presidency/Government Communication and Information System (GCIS)/Commitments pass 1.CSV
Labels: Cleaning

#384 Update PPE.CSV
  National Departments/The Presidency/Government Communication and Information System (GCIS)/PPE.CSV
Labels: Cleaning

#385 Update and rename BRAND SA - Report on covid expenditure - Table 1.cs…
  National Departments/The Presidency/Brand South Africa/Brand SA - covid expenditure PPE employees pass 1.csv
Labels: Cleaning

#386 Update and rename BRAND SA - Report on covid expenditure - Table 2.cs…
  National Departments/The Presidency/Brand South Africa/BRAND SA - Report on covid expenditure - Table 2.csv
  National Departments/The Presidency/Brand South Africa/BRAND SA - Report on covid expenditure - ppe brand and marketing.csv
Labels: Cleaning

#387 Update and rename BRAND SA - Report on covid expenditure - Table 3.cs…
  National Departments/The Presidency/Brand South Africa/BRAND SA - Report on covid expenditure - Table 3.csv
  National Departments/The Presidency/Brand South Africa/BRAND SA - Report on covid expenditure - non-covid.csv
Labels: Cleaning

#390 Update DIRCO - Information related to quotations for COVID-19 procure…
  National Departments/Department of International Relations and Cooperation (DIRCO)/DIRCO - Information related to quotations for COVID-19 procurement - with explanatory notes.csv
Labels: Cleaning

#187 DSD - NDA - pass1
  National Departments/Department of Social Development (DSD)/National Development Agency (NDA)/COVID-19 ppe pass 1.csv
Labels: hacktoberfest-accepted

#392 Update COVID-19 volunteer pass 1.csv
  National Departments/Department of Social Development (DSD)/National Development Agency (NDA)/COVID-19 volunteer pass 1.csv
Labels: Cleaning

#393 Update COVID-19 ppe pass 1.csv
  National Departments/Department of Social Development (DSD)/National Development Agency (NDA)/COVID-19 ppe pass 1.csv
Labels: Cleaning

#297 Create Department of Communications and Digital Technologies (DCDT) -…
  Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1 Part A.csv
Labels: hacktoberfest-accepted

#394 Update and rename Department of Communications and Digital Technologi…
  Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1 Part A.csv
  National Deparmtents/Department of Communications and Digital Technologies (DCDT)/SAPO pass 1 Part A.csv
Labels: Cleaning

#298 Create Create Department of Communications and Digital Technologies (…
  Create Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1 Part B.csv
Labels: hacktoberfest-accepted

#395 Update and rename Create Department of Communications and Digital Tec…
  Create Department of Communications and Digital Technologies (DCDT) - South African Post Office (SAPO) pass 1 Part B.csv
  National Departments/Department of Communications and Digital Technologies (DCDT)/SAPO pass 1 Part B.csv
Labels: Cleaning

#398 Update Perishable Products Export Control Board (PPECB) ppe pass 1.csv
  National Departments/Department of Agriculture, Land Reform and Rural Development (DALRRD)/Perishable Products Export Control Board (PPECB) ppe pass 1.csv
Labels: Cleaning

#399 Update DETAIL PROCUREMENT REPORT COVID19.CSV
  National Departments/Department of Agriculture, Land Reform and Rural Development (DALRRD)/DETAIL PROCUREMENT REPORT COVID19.CSV
Labels: Cleaning

#400 Update and rename DEFENCE - COVID EXPENDITURE.csv to DEFENCE - COVID …
  National Departments/Department of Defence/DEFENCE - COVID EXPENDITURE pass 1.csv
  National Departments/Department of Defence/DEFENCE - COVID EXPENDITURE.csv
Labels: Cleaning

#169 tabula-HOME AFFAIRS - DETAIL COVID 19 PROCUREMENT.csv
  National Departments/Department of Home Affairs (DHA)/HOME AFFAIRS - DETAIL COVID 19 PROCUREMENT.csv
Labels: hacktoberfest-accepted

#401 Update HOME AFFAIRS - DETAIL COVID 19 PROCUREMENT.csv
  National Departments/Department of Home Affairs (DHA)/HOME AFFAIRS - DETAIL COVID 19 PROCUREMENT.csv
Labels: Cleaning

#402 Update and rename tabula-DOJ CD - Fumigation Procurement from 1 March…
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/DOJ CD - Fumigation Procurement from 1 March - 29 July 2020.csv
  National Departments/Department of Justice and Constitutional Development (DoJ&CD)/tabula-DOJ CD - Fumigation Procurement from 1 March - 29 July 2020.csv
Labels: Cleaning
